### ISSUE TITLE
Make self-signed certificates work for development

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront-api#287]
If the connected Magento (1.9 in our case) shop uses a self-signed certificate, e.g. in development environment, the API will drop the error message `Error occured: Error: self signed certificate` and won’t be able to connect to your Magento instance using e.g. `DivanteLtd/magento1-vsbridge` and `DivanteLtd/magento1-vsbridge-client`.

To prevent this behavior and make a dev environment work, you can disable TLS rejection using an env variable called `NODE_TLS_REJECT_UNAUTHORIZED`.

In our case we added it to our `docker-compose` file like:
```yaml
…
services:
  vsf-api-app:
    image: divante/vue-storefront-api
    …
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    …
```

**!!! Of course, this shouldn't be used in a production environment.**
