### ISSUE TITLE
Multiple errors in production mode

### ISSUE THREAD

**Issue by phoenix-bjoern** [DivanteLtd/vue-storefront-api#85]
When changing "VS_ENV: dev" to "VS_ENV: prod" in docker-compose.nodejs.yml there are multiple errors when "docker-compose -f docker-compose.yml -f docker-compose.nodejs.yml up" is executed.

First of all ecosystem.json is not found:
```
app_1     | [PM2] PM2 Successfully daemonized
app_1     | [PM2][ERROR] File ecosystem.json not found
app_1     | ┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
app_1     | │ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
app_1     | └──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
app_1     |  Use "pm2 show <id|name>" to get more details about an app
app_1     | error Command failed with exit code 1.
```

You can mount ecosystem.json from the git root directory add in docker-compose.nodejs.yml like this:
```
    environment:
      VS_ENV: prod
    volumes:
      - './config:/var/www/config'
      - './migrations:/var/www/migrations'
      - './package.json:/var/www/package.json'
      - './scripts:/var/www/scripts'
      - './src:/var/www/src'
      - './var:/var/www/var'
      - './ecosystem.json:/var/www/ecosystem.json'
```
Then the output looks better but the container exits anyway:

```
app_1     | [PM2] PM2 Successfully daemonized
app_1     | [PM2][WARN] Applications api not running, starting...
app_1     | [PM2] App [api] launched (1 instances)
app_1     | ┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
app_1     | │ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
app_1     | ├──────────┼────┼──────┼─────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
app_1     | │ api      │ 0  │ fork │ 83  │ online │ 0       │ 0s     │ 2%  │ 23.0 MB   │ root │ disabled │
app_1     | └──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
app_1     |  Use "pm2 show <id|name>" to get more details about an app
app_1     | Done in 3.59s.
...
vue-storefront-api_app_1 exited with code 0
```

Not sure what exactly wents wrong in production mode.
